# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAuth0PostRegistrationRequest(TypedDict):
    email: str

    user_id: str

class OptionalAuth0PostRegistrationRequest(TypedDict, total=False):
    created_at: str

    email_verified: bool

    extra_info: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    family_name: str

    given_name: str

    name: str

    nickname: str

    phone_number: str

    phone_verified: bool

    picture: str

class Auth0PostRegistrationRequest(RequiredAuth0PostRegistrationRequest, OptionalAuth0PostRegistrationRequest):
    pass
