# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBillingSubscription(TypedDict):
    description: str

    amount: typing.Union[int, float]

    currency: str

    current_period_end: int

    current_period_start: int

    latest_invoice: str

    product: str

    quantity: int

    start_date: int

class OptionalBillingSubscription(TypedDict, total=False):
    pass

class BillingSubscription(RequiredBillingSubscription, OptionalBillingSubscription):
    pass
