# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pulze_ai_python_sdk.type.payment_details_balance import PaymentDetailsBalance
from pulze_ai_python_sdk.type.subscription_paused import SubscriptionPaused
from pulze_ai_python_sdk.type.user_details import UserDetails

class RequiredFrontendSettings(TypedDict):
    # Balance details
    balance: PaymentDetailsBalance

    # The currency of the user. Currently only \"USD\".
    currency: str

    # False when it's the user's first login/signup for an organization
    did_onboarding_setup: bool

    # True if the email was verified
    email_verified: bool

    # The basic information for the user
    user_details: UserDetails

class OptionalFrontendSettings(TypedDict, total=False):
    # Date of last accepted Privacy Policy
    privacy_accepted: datetime

    # Returned to the frontend when the subscription has been paused for any reason.
    subscription_paused: SubscriptionPaused

    # Date of last accepted Terms of Service
    terms_accepted: datetime

class FrontendSettings(RequiredFrontendSettings, OptionalFrontendSettings):
    pass
