# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredOrgUsage(TypedDict):
    # Number of tokens the response used
    completion_tokens: int

    # Cost (in $) of the response
    completion_tokens_cost: typing.Union[int, float]

    # Cost (in $) saved in the completion costs comparison to the benchmark model
    completion_tokens_cost_savings: typing.Union[int, float]

    # The number of active apps this Organization has
    num_apps: int

    # The number of requests this Organization has performed in the current cycle
    num_requests: int

    # The Org's ID
    org_id: str

    # Number of tokens the request used
    prompt_tokens: int

    # Cost (in $) of the prompt
    prompt_tokens_cost: typing.Union[int, float]

    # Cost (in $) saved in the prompt costs comparison to the benchmark model
    prompt_tokens_cost_savings: typing.Union[int, float]

    # Number of tokens of (request + response)
    total_tokens: int

    # Cost (in $) of the (request + response)
    total_tokens_cost: typing.Union[int, float]

    # Cost (in $) saved in total, in comparison to the benchmark model
    total_tokens_cost_savings: typing.Union[int, float]

class OptionalOrgUsage(TypedDict, total=False):
    pass

class OrgUsage(RequiredOrgUsage, OptionalOrgUsage):
    pass
