# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pulze_ai_python_sdk.type.pulze_model_with_score import PulzeModelWithScore

class RequiredPulzeEngineModelRanking(TypedDict):
    pass

class OptionalPulzeEngineModelRanking(TypedDict, total=False):
    # A list of the best models for the given prompt+config, sorted by overall score descending.
    models: typing.List[PulzeModelWithScore]

class PulzeEngineModelRanking(RequiredPulzeEngineModelRanking, OptionalPulzeEngineModelRanking):
    pass
