# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class AppWithModelUpdatesInfo(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "app",
            "model_settings",
        }
        
        class properties:
        
            @staticmethod
            def app() -> typing.Type['App']:
                return App
        
            @staticmethod
            def model_settings() -> typing.Type['AppWithModelUpdatesInfoModelSettings']:
                return AppWithModelUpdatesInfoModelSettings
            
            
            class files(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AppCustomData']:
                        return AppCustomData
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['AppCustomData'], typing.List['AppCustomData']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'files':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AppCustomData':
                    return super().__getitem__(i)
            __annotations__ = {
                "app": app,
                "model_settings": model_settings,
                "files": files,
            }
    
    app: 'App'
    model_settings: 'AppWithModelUpdatesInfoModelSettings'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["app"]) -> 'App': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["model_settings"]) -> 'AppWithModelUpdatesInfoModelSettings': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["files"]) -> MetaOapg.properties.files: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["app", "model_settings", "files", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["app"]) -> 'App': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["model_settings"]) -> 'AppWithModelUpdatesInfoModelSettings': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["files"]) -> typing.Union[MetaOapg.properties.files, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["app", "model_settings", "files", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        app: 'App',
        model_settings: 'AppWithModelUpdatesInfoModelSettings',
        files: typing.Union[MetaOapg.properties.files, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AppWithModelUpdatesInfo':
        return super().__new__(
            cls,
            *args,
            app=app,
            model_settings=model_settings,
            files=files,
            _configuration=_configuration,
            **kwargs,
        )

from pulze_ai_python_sdk.model.app import App
from pulze_ai_python_sdk.model.app_custom_data import AppCustomData
from pulze_ai_python_sdk.model.app_with_model_updates_info_model_settings import AppWithModelUpdatesInfoModelSettings
