# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class BillingSubscription(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "amount",
            "product",
            "latest_invoice",
            "quantity",
            "description",
            "currency",
            "current_period_end",
            "current_period_start",
            "start_date",
        }
        
        class properties:
            description = schemas.StrSchema
            amount = schemas.NumberSchema
            currency = schemas.StrSchema
            current_period_end = schemas.IntSchema
            current_period_start = schemas.IntSchema
            latest_invoice = schemas.StrSchema
            product = schemas.StrSchema
            quantity = schemas.IntSchema
            start_date = schemas.IntSchema
            __annotations__ = {
                "description": description,
                "amount": amount,
                "currency": currency,
                "current_period_end": current_period_end,
                "current_period_start": current_period_start,
                "latest_invoice": latest_invoice,
                "product": product,
                "quantity": quantity,
                "start_date": start_date,
            }
    
    amount: MetaOapg.properties.amount
    product: MetaOapg.properties.product
    latest_invoice: MetaOapg.properties.latest_invoice
    quantity: MetaOapg.properties.quantity
    description: MetaOapg.properties.description
    currency: MetaOapg.properties.currency
    current_period_end: MetaOapg.properties.current_period_end
    current_period_start: MetaOapg.properties.current_period_start
    start_date: MetaOapg.properties.start_date
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["current_period_end"]) -> MetaOapg.properties.current_period_end: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["current_period_start"]) -> MetaOapg.properties.current_period_start: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["latest_invoice"]) -> MetaOapg.properties.latest_invoice: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["product"]) -> MetaOapg.properties.product: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["quantity"]) -> MetaOapg.properties.quantity: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["start_date"]) -> MetaOapg.properties.start_date: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["description", "amount", "currency", "current_period_end", "current_period_start", "latest_invoice", "product", "quantity", "start_date", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["current_period_end"]) -> MetaOapg.properties.current_period_end: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["current_period_start"]) -> MetaOapg.properties.current_period_start: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["latest_invoice"]) -> MetaOapg.properties.latest_invoice: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["product"]) -> MetaOapg.properties.product: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["quantity"]) -> MetaOapg.properties.quantity: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["start_date"]) -> MetaOapg.properties.start_date: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["description", "amount", "currency", "current_period_end", "current_period_start", "latest_invoice", "product", "quantity", "start_date", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, float, ],
        product: typing.Union[MetaOapg.properties.product, str, ],
        latest_invoice: typing.Union[MetaOapg.properties.latest_invoice, str, ],
        quantity: typing.Union[MetaOapg.properties.quantity, decimal.Decimal, int, ],
        description: typing.Union[MetaOapg.properties.description, str, ],
        currency: typing.Union[MetaOapg.properties.currency, str, ],
        current_period_end: typing.Union[MetaOapg.properties.current_period_end, decimal.Decimal, int, ],
        current_period_start: typing.Union[MetaOapg.properties.current_period_start, decimal.Decimal, int, ],
        start_date: typing.Union[MetaOapg.properties.start_date, decimal.Decimal, int, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BillingSubscription':
        return super().__new__(
            cls,
            *args,
            amount=amount,
            product=product,
            latest_invoice=latest_invoice,
            quantity=quantity,
            description=description,
            currency=currency,
            current_period_end=current_period_end,
            current_period_start=current_period_start,
            start_date=start_date,
            _configuration=_configuration,
            **kwargs,
        )
