# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class BillingPaymentInfo(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "subscriptions",
            "balance",
            "payments",
        }
        
        class properties:
        
            @staticmethod
            def balance() -> typing.Type['PaymentDetailsBalance']:
                return PaymentDetailsBalance
        
            @staticmethod
            def payments() -> typing.Type['BillingPaymentInfoPayments']:
                return BillingPaymentInfoPayments
            
            
            class subscriptions(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['BillingSubscription']:
                        return BillingSubscription
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['BillingSubscription'], typing.List['BillingSubscription']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'subscriptions':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'BillingSubscription':
                    return super().__getitem__(i)
            default_card = schemas.StrSchema
        
            @staticmethod
            def discount() -> typing.Type['BillingPaymentCoupon']:
                return BillingPaymentCoupon
            __annotations__ = {
                "balance": balance,
                "payments": payments,
                "subscriptions": subscriptions,
                "default_card": default_card,
                "discount": discount,
            }
    
    subscriptions: MetaOapg.properties.subscriptions
    balance: 'PaymentDetailsBalance'
    payments: 'BillingPaymentInfoPayments'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["balance"]) -> 'PaymentDetailsBalance': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payments"]) -> 'BillingPaymentInfoPayments': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subscriptions"]) -> MetaOapg.properties.subscriptions: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["default_card"]) -> MetaOapg.properties.default_card: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["discount"]) -> 'BillingPaymentCoupon': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["balance", "payments", "subscriptions", "default_card", "discount", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["balance"]) -> 'PaymentDetailsBalance': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payments"]) -> 'BillingPaymentInfoPayments': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subscriptions"]) -> MetaOapg.properties.subscriptions: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["default_card"]) -> typing.Union[MetaOapg.properties.default_card, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["discount"]) -> typing.Union['BillingPaymentCoupon', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["balance", "payments", "subscriptions", "default_card", "discount", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        subscriptions: typing.Union[MetaOapg.properties.subscriptions, list, tuple, ],
        balance: 'PaymentDetailsBalance',
        payments: 'BillingPaymentInfoPayments',
        default_card: typing.Union[MetaOapg.properties.default_card, str, schemas.Unset] = schemas.unset,
        discount: typing.Union['BillingPaymentCoupon', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BillingPaymentInfo':
        return super().__new__(
            cls,
            *args,
            subscriptions=subscriptions,
            balance=balance,
            payments=payments,
            default_card=default_card,
            discount=discount,
            _configuration=_configuration,
            **kwargs,
        )

from pulze_ai_python_sdk.model.billing_payment_coupon import BillingPaymentCoupon
from pulze_ai_python_sdk.model.billing_payment_info_payments import BillingPaymentInfoPayments
from pulze_ai_python_sdk.model.billing_subscription import BillingSubscription
from pulze_ai_python_sdk.model.payment_details_balance import PaymentDetailsBalance
