# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class ConversationShareRequestIds(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    A list (of list) of Request IDs of all the messages that need to be shared in the playground.
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['ConversationShareRequestIdsItem']:
            return ConversationShareRequestIdsItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['ConversationShareRequestIdsItem'], typing.List['ConversationShareRequestIdsItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ConversationShareRequestIds':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'ConversationShareRequestIdsItem':
        return super().__getitem__(i)

from pulze_ai_python_sdk.model.conversation_share_request_ids_item import ConversationShareRequestIdsItem
