# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class ConversationShare(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "shared_on",
            "share_hash",
            "title",
        }
        
        class properties:
            title = schemas.StrSchema
            share_hash = schemas.StrSchema
            shared_on = schemas.DateTimeSchema
            auth0_id = schemas.StrSchema
            continuation_of = schemas.StrSchema
            hashed_ids = schemas.StrSchema
            is_public = schemas.BoolSchema
            org_id = schemas.UUIDSchema
            __annotations__ = {
                "title": title,
                "share_hash": share_hash,
                "shared_on": shared_on,
                "auth0_id": auth0_id,
                "continuation_of": continuation_of,
                "hashed_ids": hashed_ids,
                "is_public": is_public,
                "org_id": org_id,
            }
    
    shared_on: MetaOapg.properties.shared_on
    share_hash: MetaOapg.properties.share_hash
    title: MetaOapg.properties.title
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["share_hash"]) -> MetaOapg.properties.share_hash: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shared_on"]) -> MetaOapg.properties.shared_on: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["auth0_id"]) -> MetaOapg.properties.auth0_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["continuation_of"]) -> MetaOapg.properties.continuation_of: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hashed_ids"]) -> MetaOapg.properties.hashed_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_public"]) -> MetaOapg.properties.is_public: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["org_id"]) -> MetaOapg.properties.org_id: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["title", "share_hash", "shared_on", "auth0_id", "continuation_of", "hashed_ids", "is_public", "org_id", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["share_hash"]) -> MetaOapg.properties.share_hash: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shared_on"]) -> MetaOapg.properties.shared_on: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["auth0_id"]) -> typing.Union[MetaOapg.properties.auth0_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["continuation_of"]) -> typing.Union[MetaOapg.properties.continuation_of, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hashed_ids"]) -> typing.Union[MetaOapg.properties.hashed_ids, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_public"]) -> typing.Union[MetaOapg.properties.is_public, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["org_id"]) -> typing.Union[MetaOapg.properties.org_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["title", "share_hash", "shared_on", "auth0_id", "continuation_of", "hashed_ids", "is_public", "org_id", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        shared_on: typing.Union[MetaOapg.properties.shared_on, str, datetime, ],
        share_hash: typing.Union[MetaOapg.properties.share_hash, str, ],
        title: typing.Union[MetaOapg.properties.title, str, ],
        auth0_id: typing.Union[MetaOapg.properties.auth0_id, str, schemas.Unset] = schemas.unset,
        continuation_of: typing.Union[MetaOapg.properties.continuation_of, str, schemas.Unset] = schemas.unset,
        hashed_ids: typing.Union[MetaOapg.properties.hashed_ids, str, schemas.Unset] = schemas.unset,
        is_public: typing.Union[MetaOapg.properties.is_public, bool, schemas.Unset] = schemas.unset,
        org_id: typing.Union[MetaOapg.properties.org_id, str, uuid.UUID, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ConversationShare':
        return super().__new__(
            cls,
            *args,
            shared_on=shared_on,
            share_hash=share_hash,
            title=title,
            auth0_id=auth0_id,
            continuation_of=continuation_of,
            hashed_ids=hashed_ids,
            is_public=is_public,
            org_id=org_id,
            _configuration=_configuration,
            **kwargs,
        )
