# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class DashboardGraphData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "total",
            "color",
            "data",
            "max",
            "name",
            "interval",
            "id",
            "label",
        }
        
        class properties:
            color = schemas.StrSchema
            
            
            class data(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['StatsPopulatedGraphResult']:
                        return StatsPopulatedGraphResult
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['StatsPopulatedGraphResult'], typing.List['StatsPopulatedGraphResult']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'data':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'StatsPopulatedGraphResult':
                    return super().__getitem__(i)
            id = schemas.StrSchema
            interval = schemas.StrSchema
            label = schemas.StrSchema
            max = schemas.NumberSchema
            name = schemas.StrSchema
            total = schemas.NumberSchema
            cumulative = schemas.BoolSchema
            large = schemas.BoolSchema
            __annotations__ = {
                "color": color,
                "data": data,
                "id": id,
                "interval": interval,
                "label": label,
                "max": max,
                "name": name,
                "total": total,
                "cumulative": cumulative,
                "large": large,
            }
    
    total: MetaOapg.properties.total
    color: MetaOapg.properties.color
    data: MetaOapg.properties.data
    max: MetaOapg.properties.max
    name: MetaOapg.properties.name
    interval: MetaOapg.properties.interval
    id: MetaOapg.properties.id
    label: MetaOapg.properties.label
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["color"]) -> MetaOapg.properties.color: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["data"]) -> MetaOapg.properties.data: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["interval"]) -> MetaOapg.properties.interval: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["label"]) -> MetaOapg.properties.label: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max"]) -> MetaOapg.properties.max: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["total"]) -> MetaOapg.properties.total: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cumulative"]) -> MetaOapg.properties.cumulative: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["large"]) -> MetaOapg.properties.large: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["color", "data", "id", "interval", "label", "max", "name", "total", "cumulative", "large", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["color"]) -> MetaOapg.properties.color: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["data"]) -> MetaOapg.properties.data: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["interval"]) -> MetaOapg.properties.interval: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["label"]) -> MetaOapg.properties.label: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max"]) -> MetaOapg.properties.max: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["total"]) -> MetaOapg.properties.total: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cumulative"]) -> typing.Union[MetaOapg.properties.cumulative, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["large"]) -> typing.Union[MetaOapg.properties.large, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["color", "data", "id", "interval", "label", "max", "name", "total", "cumulative", "large", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        total: typing.Union[MetaOapg.properties.total, decimal.Decimal, int, float, ],
        color: typing.Union[MetaOapg.properties.color, str, ],
        data: typing.Union[MetaOapg.properties.data, list, tuple, ],
        max: typing.Union[MetaOapg.properties.max, decimal.Decimal, int, float, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        interval: typing.Union[MetaOapg.properties.interval, str, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        label: typing.Union[MetaOapg.properties.label, str, ],
        cumulative: typing.Union[MetaOapg.properties.cumulative, bool, schemas.Unset] = schemas.unset,
        large: typing.Union[MetaOapg.properties.large, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DashboardGraphData':
        return super().__new__(
            cls,
            *args,
            total=total,
            color=color,
            data=data,
            max=max,
            name=name,
            interval=interval,
            id=id,
            label=label,
            cumulative=cumulative,
            large=large,
            _configuration=_configuration,
            **kwargs,
        )

from pulze_ai_python_sdk.model.stats_populated_graph_result import StatsPopulatedGraphResult
