# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class FeaturesForSubscriptionDescriptions(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    See FeaturesForSubscription for more info!
This class is a duplicate so if anything gets renamed on the parent class, this one will error.
    """


    class MetaOapg:
        required = {
            "personalized_llm_routing",
            "prompt_models",
            "llm_routing",
            "support_level_readable",
            "max_tokens_readable",
            "fine_tuning",
            "flowz",
            "customer_success",
            "max_apps_readable",
            "prompts",
        }
        
        class properties:
            customer_success = schemas.StrSchema
            fine_tuning = schemas.StrSchema
            flowz = schemas.StrSchema
            llm_routing = schemas.StrSchema
            max_apps_readable = schemas.StrSchema
            max_tokens_readable = schemas.StrSchema
            personalized_llm_routing = schemas.StrSchema
            prompt_models = schemas.StrSchema
            prompts = schemas.StrSchema
            support_level_readable = schemas.StrSchema
            __annotations__ = {
                "customer_success": customer_success,
                "fine_tuning": fine_tuning,
                "flowz": flowz,
                "llm_routing": llm_routing,
                "max_apps_readable": max_apps_readable,
                "max_tokens_readable": max_tokens_readable,
                "personalized_llm_routing": personalized_llm_routing,
                "prompt_models": prompt_models,
                "prompts": prompts,
                "support_level_readable": support_level_readable,
            }
    
    personalized_llm_routing: MetaOapg.properties.personalized_llm_routing
    prompt_models: MetaOapg.properties.prompt_models
    llm_routing: MetaOapg.properties.llm_routing
    support_level_readable: MetaOapg.properties.support_level_readable
    max_tokens_readable: MetaOapg.properties.max_tokens_readable
    fine_tuning: MetaOapg.properties.fine_tuning
    flowz: MetaOapg.properties.flowz
    customer_success: MetaOapg.properties.customer_success
    max_apps_readable: MetaOapg.properties.max_apps_readable
    prompts: MetaOapg.properties.prompts
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customer_success"]) -> MetaOapg.properties.customer_success: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fine_tuning"]) -> MetaOapg.properties.fine_tuning: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["flowz"]) -> MetaOapg.properties.flowz: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["llm_routing"]) -> MetaOapg.properties.llm_routing: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_apps_readable"]) -> MetaOapg.properties.max_apps_readable: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max_tokens_readable"]) -> MetaOapg.properties.max_tokens_readable: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["personalized_llm_routing"]) -> MetaOapg.properties.personalized_llm_routing: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["prompt_models"]) -> MetaOapg.properties.prompt_models: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["prompts"]) -> MetaOapg.properties.prompts: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["support_level_readable"]) -> MetaOapg.properties.support_level_readable: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["customer_success", "fine_tuning", "flowz", "llm_routing", "max_apps_readable", "max_tokens_readable", "personalized_llm_routing", "prompt_models", "prompts", "support_level_readable", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customer_success"]) -> MetaOapg.properties.customer_success: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fine_tuning"]) -> MetaOapg.properties.fine_tuning: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["flowz"]) -> MetaOapg.properties.flowz: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["llm_routing"]) -> MetaOapg.properties.llm_routing: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_apps_readable"]) -> MetaOapg.properties.max_apps_readable: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max_tokens_readable"]) -> MetaOapg.properties.max_tokens_readable: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["personalized_llm_routing"]) -> MetaOapg.properties.personalized_llm_routing: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["prompt_models"]) -> MetaOapg.properties.prompt_models: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["prompts"]) -> MetaOapg.properties.prompts: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["support_level_readable"]) -> MetaOapg.properties.support_level_readable: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["customer_success", "fine_tuning", "flowz", "llm_routing", "max_apps_readable", "max_tokens_readable", "personalized_llm_routing", "prompt_models", "prompts", "support_level_readable", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        personalized_llm_routing: typing.Union[MetaOapg.properties.personalized_llm_routing, str, ],
        prompt_models: typing.Union[MetaOapg.properties.prompt_models, str, ],
        llm_routing: typing.Union[MetaOapg.properties.llm_routing, str, ],
        support_level_readable: typing.Union[MetaOapg.properties.support_level_readable, str, ],
        max_tokens_readable: typing.Union[MetaOapg.properties.max_tokens_readable, str, ],
        fine_tuning: typing.Union[MetaOapg.properties.fine_tuning, str, ],
        flowz: typing.Union[MetaOapg.properties.flowz, str, ],
        customer_success: typing.Union[MetaOapg.properties.customer_success, str, ],
        max_apps_readable: typing.Union[MetaOapg.properties.max_apps_readable, str, ],
        prompts: typing.Union[MetaOapg.properties.prompts, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FeaturesForSubscriptionDescriptions':
        return super().__new__(
            cls,
            *args,
            personalized_llm_routing=personalized_llm_routing,
            prompt_models=prompt_models,
            llm_routing=llm_routing,
            support_level_readable=support_level_readable,
            max_tokens_readable=max_tokens_readable,
            fine_tuning=fine_tuning,
            flowz=flowz,
            customer_success=customer_success,
            max_apps_readable=max_apps_readable,
            prompts=prompts,
            _configuration=_configuration,
            **kwargs,
        )
