# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class FilterLogsRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "date_from",
        }
        
        class properties:
            date_from = schemas.DateTimeSchema
        
            @staticmethod
            def app_ids() -> typing.Type['FilterLogsRequestAppIds']:
                return FilterLogsRequestAppIds
            date_to = schemas.DateTimeSchema
        
            @staticmethod
            def labels() -> typing.Type['FilterLogsRequestLabels']:
                return FilterLogsRequestLabels
            
            
            class params(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['GetTableSortParams']:
                        return GetTableSortParams
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['GetTableSortParams'], typing.List['GetTableSortParams']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'params':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'GetTableSortParams':
                    return super().__getitem__(i)
            query = schemas.StrSchema
            __annotations__ = {
                "date_from": date_from,
                "app_ids": app_ids,
                "date_to": date_to,
                "labels": labels,
                "params": params,
                "query": query,
            }
    
    date_from: MetaOapg.properties.date_from
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_from"]) -> MetaOapg.properties.date_from: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["app_ids"]) -> 'FilterLogsRequestAppIds': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_to"]) -> MetaOapg.properties.date_to: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["labels"]) -> 'FilterLogsRequestLabels': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["params"]) -> MetaOapg.properties.params: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["query"]) -> MetaOapg.properties.query: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["date_from", "app_ids", "date_to", "labels", "params", "query", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_from"]) -> MetaOapg.properties.date_from: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["app_ids"]) -> typing.Union['FilterLogsRequestAppIds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_to"]) -> typing.Union[MetaOapg.properties.date_to, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["labels"]) -> typing.Union['FilterLogsRequestLabels', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["params"]) -> typing.Union[MetaOapg.properties.params, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["query"]) -> typing.Union[MetaOapg.properties.query, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["date_from", "app_ids", "date_to", "labels", "params", "query", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        date_from: typing.Union[MetaOapg.properties.date_from, str, datetime, ],
        app_ids: typing.Union['FilterLogsRequestAppIds', schemas.Unset] = schemas.unset,
        date_to: typing.Union[MetaOapg.properties.date_to, str, datetime, schemas.Unset] = schemas.unset,
        labels: typing.Union['FilterLogsRequestLabels', schemas.Unset] = schemas.unset,
        params: typing.Union[MetaOapg.properties.params, list, tuple, schemas.Unset] = schemas.unset,
        query: typing.Union[MetaOapg.properties.query, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FilterLogsRequest':
        return super().__new__(
            cls,
            *args,
            date_from=date_from,
            app_ids=app_ids,
            date_to=date_to,
            labels=labels,
            params=params,
            query=query,
            _configuration=_configuration,
            **kwargs,
        )

from pulze_ai_python_sdk.model.filter_logs_request_app_ids import FilterLogsRequestAppIds
from pulze_ai_python_sdk.model.filter_logs_request_labels import FilterLogsRequestLabels
from pulze_ai_python_sdk.model.get_table_sort_params import GetTableSortParams
