# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class FrontendSettings(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "did_onboarding_setup",
            "email_verified",
            "balance",
            "user_details",
            "currency",
        }
        
        class properties:
        
            @staticmethod
            def balance() -> typing.Type['PaymentDetailsBalance']:
                return PaymentDetailsBalance
            
            
            class currency(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def USD(cls):
                    return cls("USD")
            did_onboarding_setup = schemas.BoolSchema
            email_verified = schemas.BoolSchema
        
            @staticmethod
            def user_details() -> typing.Type['UserDetails']:
                return UserDetails
            privacy_accepted = schemas.DateTimeSchema
        
            @staticmethod
            def subscription_paused() -> typing.Type['SubscriptionPaused']:
                return SubscriptionPaused
            terms_accepted = schemas.DateTimeSchema
            __annotations__ = {
                "balance": balance,
                "currency": currency,
                "did_onboarding_setup": did_onboarding_setup,
                "email_verified": email_verified,
                "user_details": user_details,
                "privacy_accepted": privacy_accepted,
                "subscription_paused": subscription_paused,
                "terms_accepted": terms_accepted,
            }
    
    did_onboarding_setup: MetaOapg.properties.did_onboarding_setup
    email_verified: MetaOapg.properties.email_verified
    balance: 'PaymentDetailsBalance'
    user_details: 'UserDetails'
    currency: MetaOapg.properties.currency
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["balance"]) -> 'PaymentDetailsBalance': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["did_onboarding_setup"]) -> MetaOapg.properties.did_onboarding_setup: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email_verified"]) -> MetaOapg.properties.email_verified: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user_details"]) -> 'UserDetails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["privacy_accepted"]) -> MetaOapg.properties.privacy_accepted: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subscription_paused"]) -> 'SubscriptionPaused': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["terms_accepted"]) -> MetaOapg.properties.terms_accepted: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["balance", "currency", "did_onboarding_setup", "email_verified", "user_details", "privacy_accepted", "subscription_paused", "terms_accepted", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["balance"]) -> 'PaymentDetailsBalance': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["did_onboarding_setup"]) -> MetaOapg.properties.did_onboarding_setup: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email_verified"]) -> MetaOapg.properties.email_verified: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user_details"]) -> 'UserDetails': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["privacy_accepted"]) -> typing.Union[MetaOapg.properties.privacy_accepted, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subscription_paused"]) -> typing.Union['SubscriptionPaused', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["terms_accepted"]) -> typing.Union[MetaOapg.properties.terms_accepted, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["balance", "currency", "did_onboarding_setup", "email_verified", "user_details", "privacy_accepted", "subscription_paused", "terms_accepted", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        did_onboarding_setup: typing.Union[MetaOapg.properties.did_onboarding_setup, bool, ],
        email_verified: typing.Union[MetaOapg.properties.email_verified, bool, ],
        balance: 'PaymentDetailsBalance',
        user_details: 'UserDetails',
        currency: typing.Union[MetaOapg.properties.currency, str, ],
        privacy_accepted: typing.Union[MetaOapg.properties.privacy_accepted, str, datetime, schemas.Unset] = schemas.unset,
        subscription_paused: typing.Union['SubscriptionPaused', schemas.Unset] = schemas.unset,
        terms_accepted: typing.Union[MetaOapg.properties.terms_accepted, str, datetime, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FrontendSettings':
        return super().__new__(
            cls,
            *args,
            did_onboarding_setup=did_onboarding_setup,
            email_verified=email_verified,
            balance=balance,
            user_details=user_details,
            currency=currency,
            privacy_accepted=privacy_accepted,
            subscription_paused=subscription_paused,
            terms_accepted=terms_accepted,
            _configuration=_configuration,
            **kwargs,
        )

from pulze_ai_python_sdk.model.payment_details_balance import PaymentDetailsBalance
from pulze_ai_python_sdk.model.subscription_paused import SubscriptionPaused
from pulze_ai_python_sdk.model.user_details import UserDetails
