# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class InternalUserData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "email_verified",
            "name",
            "id",
            "invite_status",
            "type",
            "email",
        }
        
        class properties:
            email = schemas.StrSchema
            email_verified = schemas.BoolSchema
            id = schemas.StrSchema
            invite_status = schemas.StrSchema
            name = schemas.StrSchema
            type = schemas.StrSchema
            hubspot_id = schemas.StrSchema
            __annotations__ = {
                "email": email,
                "email_verified": email_verified,
                "id": id,
                "invite_status": invite_status,
                "name": name,
                "type": type,
                "hubspot_id": hubspot_id,
            }
    
    email_verified: MetaOapg.properties.email_verified
    name: MetaOapg.properties.name
    id: MetaOapg.properties.id
    invite_status: MetaOapg.properties.invite_status
    type: MetaOapg.properties.type
    email: MetaOapg.properties.email
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email_verified"]) -> MetaOapg.properties.email_verified: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["invite_status"]) -> MetaOapg.properties.invite_status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hubspot_id"]) -> MetaOapg.properties.hubspot_id: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["email", "email_verified", "id", "invite_status", "name", "type", "hubspot_id", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email_verified"]) -> MetaOapg.properties.email_verified: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["invite_status"]) -> MetaOapg.properties.invite_status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hubspot_id"]) -> typing.Union[MetaOapg.properties.hubspot_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["email", "email_verified", "id", "invite_status", "name", "type", "hubspot_id", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        email_verified: typing.Union[MetaOapg.properties.email_verified, bool, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        invite_status: typing.Union[MetaOapg.properties.invite_status, str, ],
        type: typing.Union[MetaOapg.properties.type, str, ],
        email: typing.Union[MetaOapg.properties.email, str, ],
        hubspot_id: typing.Union[MetaOapg.properties.hubspot_id, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'InternalUserData':
        return super().__new__(
            cls,
            *args,
            email_verified=email_verified,
            name=name,
            id=id,
            invite_status=invite_status,
            type=type,
            email=email,
            hubspot_id=hubspot_id,
            _configuration=_configuration,
            **kwargs,
        )
