# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class ModelDataCreatePayloadForInternal(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            description = schemas.StrSchema
            app_id = schemas.UUIDSchema
            at = schemas.StrSchema
            base_cost = schemas.StrSchema
            completion_token_cost = schemas.StrSchema
            context_window = schemas.IntSchema
            default_active = schemas.BoolSchema
            is_chat = schemas.BoolSchema
            is_gdpr = schemas.BoolSchema
            is_open_source = schemas.BoolSchema
            is_public = schemas.BoolSchema
            model = schemas.StrSchema
            org_id = schemas.UUIDSchema
            owner = schemas.StrSchema
            prompt_token_cost = schemas.StrSchema
            provider = schemas.StrSchema
            supports_functions = schemas.BoolSchema
            supports_json = schemas.BoolSchema
            supports_n = schemas.BoolSchema
            supports_penalties = schemas.BoolSchema
            supports_stream = schemas.BoolSchema
            until = schemas.StrSchema
            url = schemas.StrSchema
            __annotations__ = {
                "description": description,
                "app_id": app_id,
                "at": at,
                "base_cost": base_cost,
                "completion_token_cost": completion_token_cost,
                "context_window": context_window,
                "default_active": default_active,
                "is_chat": is_chat,
                "is_gdpr": is_gdpr,
                "is_open_source": is_open_source,
                "is_public": is_public,
                "model": model,
                "org_id": org_id,
                "owner": owner,
                "prompt_token_cost": prompt_token_cost,
                "provider": provider,
                "supports_functions": supports_functions,
                "supports_json": supports_json,
                "supports_n": supports_n,
                "supports_penalties": supports_penalties,
                "supports_stream": supports_stream,
                "until": until,
                "url": url,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["app_id"]) -> MetaOapg.properties.app_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["at"]) -> MetaOapg.properties.at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["base_cost"]) -> MetaOapg.properties.base_cost: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["completion_token_cost"]) -> MetaOapg.properties.completion_token_cost: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["context_window"]) -> MetaOapg.properties.context_window: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["default_active"]) -> MetaOapg.properties.default_active: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_chat"]) -> MetaOapg.properties.is_chat: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_gdpr"]) -> MetaOapg.properties.is_gdpr: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_open_source"]) -> MetaOapg.properties.is_open_source: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_public"]) -> MetaOapg.properties.is_public: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["model"]) -> MetaOapg.properties.model: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["org_id"]) -> MetaOapg.properties.org_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["owner"]) -> MetaOapg.properties.owner: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["prompt_token_cost"]) -> MetaOapg.properties.prompt_token_cost: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["provider"]) -> MetaOapg.properties.provider: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["supports_functions"]) -> MetaOapg.properties.supports_functions: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["supports_json"]) -> MetaOapg.properties.supports_json: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["supports_n"]) -> MetaOapg.properties.supports_n: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["supports_penalties"]) -> MetaOapg.properties.supports_penalties: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["supports_stream"]) -> MetaOapg.properties.supports_stream: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["until"]) -> MetaOapg.properties.until: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["url"]) -> MetaOapg.properties.url: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["description", "app_id", "at", "base_cost", "completion_token_cost", "context_window", "default_active", "is_chat", "is_gdpr", "is_open_source", "is_public", "model", "org_id", "owner", "prompt_token_cost", "provider", "supports_functions", "supports_json", "supports_n", "supports_penalties", "supports_stream", "until", "url", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["app_id"]) -> typing.Union[MetaOapg.properties.app_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["at"]) -> typing.Union[MetaOapg.properties.at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["base_cost"]) -> typing.Union[MetaOapg.properties.base_cost, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["completion_token_cost"]) -> typing.Union[MetaOapg.properties.completion_token_cost, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["context_window"]) -> typing.Union[MetaOapg.properties.context_window, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["default_active"]) -> typing.Union[MetaOapg.properties.default_active, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_chat"]) -> typing.Union[MetaOapg.properties.is_chat, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_gdpr"]) -> typing.Union[MetaOapg.properties.is_gdpr, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_open_source"]) -> typing.Union[MetaOapg.properties.is_open_source, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_public"]) -> typing.Union[MetaOapg.properties.is_public, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["model"]) -> typing.Union[MetaOapg.properties.model, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["org_id"]) -> typing.Union[MetaOapg.properties.org_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["owner"]) -> typing.Union[MetaOapg.properties.owner, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["prompt_token_cost"]) -> typing.Union[MetaOapg.properties.prompt_token_cost, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["provider"]) -> typing.Union[MetaOapg.properties.provider, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["supports_functions"]) -> typing.Union[MetaOapg.properties.supports_functions, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["supports_json"]) -> typing.Union[MetaOapg.properties.supports_json, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["supports_n"]) -> typing.Union[MetaOapg.properties.supports_n, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["supports_penalties"]) -> typing.Union[MetaOapg.properties.supports_penalties, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["supports_stream"]) -> typing.Union[MetaOapg.properties.supports_stream, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["until"]) -> typing.Union[MetaOapg.properties.until, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["url"]) -> typing.Union[MetaOapg.properties.url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["description", "app_id", "at", "base_cost", "completion_token_cost", "context_window", "default_active", "is_chat", "is_gdpr", "is_open_source", "is_public", "model", "org_id", "owner", "prompt_token_cost", "provider", "supports_functions", "supports_json", "supports_n", "supports_penalties", "supports_stream", "until", "url", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        app_id: typing.Union[MetaOapg.properties.app_id, str, uuid.UUID, schemas.Unset] = schemas.unset,
        at: typing.Union[MetaOapg.properties.at, str, schemas.Unset] = schemas.unset,
        base_cost: typing.Union[MetaOapg.properties.base_cost, str, schemas.Unset] = schemas.unset,
        completion_token_cost: typing.Union[MetaOapg.properties.completion_token_cost, str, schemas.Unset] = schemas.unset,
        context_window: typing.Union[MetaOapg.properties.context_window, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        default_active: typing.Union[MetaOapg.properties.default_active, bool, schemas.Unset] = schemas.unset,
        is_chat: typing.Union[MetaOapg.properties.is_chat, bool, schemas.Unset] = schemas.unset,
        is_gdpr: typing.Union[MetaOapg.properties.is_gdpr, bool, schemas.Unset] = schemas.unset,
        is_open_source: typing.Union[MetaOapg.properties.is_open_source, bool, schemas.Unset] = schemas.unset,
        is_public: typing.Union[MetaOapg.properties.is_public, bool, schemas.Unset] = schemas.unset,
        model: typing.Union[MetaOapg.properties.model, str, schemas.Unset] = schemas.unset,
        org_id: typing.Union[MetaOapg.properties.org_id, str, uuid.UUID, schemas.Unset] = schemas.unset,
        owner: typing.Union[MetaOapg.properties.owner, str, schemas.Unset] = schemas.unset,
        prompt_token_cost: typing.Union[MetaOapg.properties.prompt_token_cost, str, schemas.Unset] = schemas.unset,
        provider: typing.Union[MetaOapg.properties.provider, str, schemas.Unset] = schemas.unset,
        supports_functions: typing.Union[MetaOapg.properties.supports_functions, bool, schemas.Unset] = schemas.unset,
        supports_json: typing.Union[MetaOapg.properties.supports_json, bool, schemas.Unset] = schemas.unset,
        supports_n: typing.Union[MetaOapg.properties.supports_n, bool, schemas.Unset] = schemas.unset,
        supports_penalties: typing.Union[MetaOapg.properties.supports_penalties, bool, schemas.Unset] = schemas.unset,
        supports_stream: typing.Union[MetaOapg.properties.supports_stream, bool, schemas.Unset] = schemas.unset,
        until: typing.Union[MetaOapg.properties.until, str, schemas.Unset] = schemas.unset,
        url: typing.Union[MetaOapg.properties.url, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelDataCreatePayloadForInternal':
        return super().__new__(
            cls,
            *args,
            description=description,
            app_id=app_id,
            at=at,
            base_cost=base_cost,
            completion_token_cost=completion_token_cost,
            context_window=context_window,
            default_active=default_active,
            is_chat=is_chat,
            is_gdpr=is_gdpr,
            is_open_source=is_open_source,
            is_public=is_public,
            model=model,
            org_id=org_id,
            owner=owner,
            prompt_token_cost=prompt_token_cost,
            provider=provider,
            supports_functions=supports_functions,
            supports_json=supports_json,
            supports_n=supports_n,
            supports_penalties=supports_penalties,
            supports_stream=supports_stream,
            until=until,
            url=url,
            _configuration=_configuration,
            **kwargs,
        )
