# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class Prompt(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "modified_on",
            "org_id",
            "description",
            "tokens",
            "id",
            "title",
            "added_on",
            "prompt",
        }
        
        class properties:
            
            
            class title(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 60
                    min_length = 1
            
            
            class description(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 200
                    min_length = 1
            added_on = schemas.DateTimeSchema
            id = schemas.UUIDSchema
            modified_on = schemas.DateTimeSchema
            org_id = schemas.UUIDSchema
            
            
            class prompt(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    regex=[{
                        'pattern': r'[\s\S]*{{prompt}}[\s\S]*',
                    }]
            tokens = schemas.IntSchema
            approved_on = schemas.DateTimeSchema
            decline_reason = schemas.StrSchema
            published_on = schemas.DateTimeSchema
            reviewed_on = schemas.DateTimeSchema
            __annotations__ = {
                "title": title,
                "description": description,
                "added_on": added_on,
                "id": id,
                "modified_on": modified_on,
                "org_id": org_id,
                "prompt": prompt,
                "tokens": tokens,
                "approved_on": approved_on,
                "decline_reason": decline_reason,
                "published_on": published_on,
                "reviewed_on": reviewed_on,
            }
    
    modified_on: MetaOapg.properties.modified_on
    org_id: MetaOapg.properties.org_id
    description: MetaOapg.properties.description
    tokens: MetaOapg.properties.tokens
    id: MetaOapg.properties.id
    title: MetaOapg.properties.title
    added_on: MetaOapg.properties.added_on
    prompt: MetaOapg.properties.prompt
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["added_on"]) -> MetaOapg.properties.added_on: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["modified_on"]) -> MetaOapg.properties.modified_on: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["org_id"]) -> MetaOapg.properties.org_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["prompt"]) -> MetaOapg.properties.prompt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tokens"]) -> MetaOapg.properties.tokens: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["approved_on"]) -> MetaOapg.properties.approved_on: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["decline_reason"]) -> MetaOapg.properties.decline_reason: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["published_on"]) -> MetaOapg.properties.published_on: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reviewed_on"]) -> MetaOapg.properties.reviewed_on: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["title", "description", "added_on", "id", "modified_on", "org_id", "prompt", "tokens", "approved_on", "decline_reason", "published_on", "reviewed_on", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["added_on"]) -> MetaOapg.properties.added_on: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["modified_on"]) -> MetaOapg.properties.modified_on: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["org_id"]) -> MetaOapg.properties.org_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["prompt"]) -> MetaOapg.properties.prompt: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tokens"]) -> MetaOapg.properties.tokens: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["approved_on"]) -> typing.Union[MetaOapg.properties.approved_on, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["decline_reason"]) -> typing.Union[MetaOapg.properties.decline_reason, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["published_on"]) -> typing.Union[MetaOapg.properties.published_on, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reviewed_on"]) -> typing.Union[MetaOapg.properties.reviewed_on, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["title", "description", "added_on", "id", "modified_on", "org_id", "prompt", "tokens", "approved_on", "decline_reason", "published_on", "reviewed_on", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        modified_on: typing.Union[MetaOapg.properties.modified_on, str, datetime, ],
        org_id: typing.Union[MetaOapg.properties.org_id, str, uuid.UUID, ],
        description: typing.Union[MetaOapg.properties.description, str, ],
        tokens: typing.Union[MetaOapg.properties.tokens, decimal.Decimal, int, ],
        id: typing.Union[MetaOapg.properties.id, str, uuid.UUID, ],
        title: typing.Union[MetaOapg.properties.title, str, ],
        added_on: typing.Union[MetaOapg.properties.added_on, str, datetime, ],
        prompt: typing.Union[MetaOapg.properties.prompt, str, ],
        approved_on: typing.Union[MetaOapg.properties.approved_on, str, datetime, schemas.Unset] = schemas.unset,
        decline_reason: typing.Union[MetaOapg.properties.decline_reason, str, schemas.Unset] = schemas.unset,
        published_on: typing.Union[MetaOapg.properties.published_on, str, datetime, schemas.Unset] = schemas.unset,
        reviewed_on: typing.Union[MetaOapg.properties.reviewed_on, str, datetime, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Prompt':
        return super().__new__(
            cls,
            *args,
            modified_on=modified_on,
            org_id=org_id,
            description=description,
            tokens=tokens,
            id=id,
            title=title,
            added_on=added_on,
            prompt=prompt,
            approved_on=approved_on,
            decline_reason=decline_reason,
            published_on=published_on,
            reviewed_on=reviewed_on,
            _configuration=_configuration,
            **kwargs,
        )
