# coding: utf-8

"""
    Pulze.ai API

    At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.  We are a VC Funded, early stage startup based in San Francisco.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pulze_ai_python_sdk import schemas  # noqa: F401


class UserOrgAccess(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "org_id",
            "org_display_name",
            "auth0_id",
            "org_name",
        }
        
        class properties:
            auth0_id = schemas.StrSchema
            org_display_name = schemas.StrSchema
            org_id = schemas.UUIDSchema
            org_name = schemas.StrSchema
            billing_email = schemas.StrSchema
            full_name = schemas.StrSchema
            is_org_setup_complete = schemas.BoolSchema
            is_personal_org = schemas.BoolSchema
            member_is_active = schemas.BoolSchema
        
            @staticmethod
            def org() -> typing.Type['Org']:
                return Org
            org_stripe_id = schemas.StrSchema
            permissions = schemas.StrSchema
            user_avatar = schemas.StrSchema
            __annotations__ = {
                "auth0_id": auth0_id,
                "org_display_name": org_display_name,
                "org_id": org_id,
                "org_name": org_name,
                "billing_email": billing_email,
                "full_name": full_name,
                "is_org_setup_complete": is_org_setup_complete,
                "is_personal_org": is_personal_org,
                "member_is_active": member_is_active,
                "org": org,
                "org_stripe_id": org_stripe_id,
                "permissions": permissions,
                "user_avatar": user_avatar,
            }
    
    org_id: MetaOapg.properties.org_id
    org_display_name: MetaOapg.properties.org_display_name
    auth0_id: MetaOapg.properties.auth0_id
    org_name: MetaOapg.properties.org_name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["auth0_id"]) -> MetaOapg.properties.auth0_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["org_display_name"]) -> MetaOapg.properties.org_display_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["org_id"]) -> MetaOapg.properties.org_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["org_name"]) -> MetaOapg.properties.org_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["billing_email"]) -> MetaOapg.properties.billing_email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["full_name"]) -> MetaOapg.properties.full_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_org_setup_complete"]) -> MetaOapg.properties.is_org_setup_complete: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_personal_org"]) -> MetaOapg.properties.is_personal_org: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["member_is_active"]) -> MetaOapg.properties.member_is_active: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["org"]) -> 'Org': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["org_stripe_id"]) -> MetaOapg.properties.org_stripe_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["permissions"]) -> MetaOapg.properties.permissions: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user_avatar"]) -> MetaOapg.properties.user_avatar: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["auth0_id", "org_display_name", "org_id", "org_name", "billing_email", "full_name", "is_org_setup_complete", "is_personal_org", "member_is_active", "org", "org_stripe_id", "permissions", "user_avatar", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["auth0_id"]) -> MetaOapg.properties.auth0_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["org_display_name"]) -> MetaOapg.properties.org_display_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["org_id"]) -> MetaOapg.properties.org_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["org_name"]) -> MetaOapg.properties.org_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["billing_email"]) -> typing.Union[MetaOapg.properties.billing_email, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["full_name"]) -> typing.Union[MetaOapg.properties.full_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_org_setup_complete"]) -> typing.Union[MetaOapg.properties.is_org_setup_complete, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_personal_org"]) -> typing.Union[MetaOapg.properties.is_personal_org, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["member_is_active"]) -> typing.Union[MetaOapg.properties.member_is_active, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["org"]) -> typing.Union['Org', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["org_stripe_id"]) -> typing.Union[MetaOapg.properties.org_stripe_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["permissions"]) -> typing.Union[MetaOapg.properties.permissions, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user_avatar"]) -> typing.Union[MetaOapg.properties.user_avatar, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["auth0_id", "org_display_name", "org_id", "org_name", "billing_email", "full_name", "is_org_setup_complete", "is_personal_org", "member_is_active", "org", "org_stripe_id", "permissions", "user_avatar", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        org_id: typing.Union[MetaOapg.properties.org_id, str, uuid.UUID, ],
        org_display_name: typing.Union[MetaOapg.properties.org_display_name, str, ],
        auth0_id: typing.Union[MetaOapg.properties.auth0_id, str, ],
        org_name: typing.Union[MetaOapg.properties.org_name, str, ],
        billing_email: typing.Union[MetaOapg.properties.billing_email, str, schemas.Unset] = schemas.unset,
        full_name: typing.Union[MetaOapg.properties.full_name, str, schemas.Unset] = schemas.unset,
        is_org_setup_complete: typing.Union[MetaOapg.properties.is_org_setup_complete, bool, schemas.Unset] = schemas.unset,
        is_personal_org: typing.Union[MetaOapg.properties.is_personal_org, bool, schemas.Unset] = schemas.unset,
        member_is_active: typing.Union[MetaOapg.properties.member_is_active, bool, schemas.Unset] = schemas.unset,
        org: typing.Union['Org', schemas.Unset] = schemas.unset,
        org_stripe_id: typing.Union[MetaOapg.properties.org_stripe_id, str, schemas.Unset] = schemas.unset,
        permissions: typing.Union[MetaOapg.properties.permissions, str, schemas.Unset] = schemas.unset,
        user_avatar: typing.Union[MetaOapg.properties.user_avatar, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UserOrgAccess':
        return super().__new__(
            cls,
            *args,
            org_id=org_id,
            org_display_name=org_display_name,
            auth0_id=auth0_id,
            org_name=org_name,
            billing_email=billing_email,
            full_name=full_name,
            is_org_setup_complete=is_org_setup_complete,
            is_personal_org=is_personal_org,
            member_is_active=member_is_active,
            org=org,
            org_stripe_id=org_stripe_id,
            permissions=permissions,
            user_avatar=user_avatar,
            _configuration=_configuration,
            **kwargs,
        )

from pulze_ai_python_sdk.model.org import Org
